services:
  postgres:
    image: postgres:16-alpine
    container_name: bingo-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bingo

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: bingo-api

    depends_on:
      - postgres

    ports:
      - "5001:5000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bingo?schema=public

    command: >
      sh -c "
      npx prisma migrate deploy &&
      npx tsx src/server.ts
      "

volumes:
  postgres_data: